export const users = [
    {
        id: 1,
        username: 'admin',
        password: 'admin',
        role: 'admin',
        firstName: 'Admin',
        lastName: 'Account',
        email: 'admin@phishingoperations.com',
        organization: 'The Admin Org',
        created: 'Wed Mar 17 2026 8:23:00 GMT+0800',
    },
    {
        id: 2,
        username: 'admin2',
        password: 'admin2',
        role: 'admin',
        firstName: 'Admin2',
        lastName: 'Account2',
        email: 'admin2@phishingoperations.com',
        organization: 'The Admin Org',
        created: 'Wed Mar 18 2026 10:07:00 GMT+0800',
    },
    {
        id: 3,
        username: 'hr1',
        password: 'hr1',
        role: 'hr',
        firstName: 'HR1',
        lastName: 'Account1',
        email: 'hr1@phishingoperations.com',
        organization: 'The Admin Org',
        created: 'Wed Mar 18 2026 10:10:00 GMT+0800',
    },
]
